# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"exception_handler": "simplydrug.ipynb",
         "add_layout": "simplydrug.ipynb",
         "order_wells": "simplydrug.ipynb",
         "hts_heatmap": "simplydrug.ipynb",
         "sum_statistics": "simplydrug.ipynb",
         "normalize_z": "simplydrug.ipynb",
         "histogram_feature": "simplydrug.ipynb",
         "calculate_growth_score": "simplydrug.ipynb",
         "filter_curves": "simplydrug.ipynb",
         "ll4": "simplydrug.ipynb",
         "inv_log": "simplydrug.ipynb",
         "pDose": "simplydrug.ipynb",
         "dose_response": "simplydrug.ipynb",
         "plot_dr_viability": "simplydrug.ipynb",
         "prune_compound": "simplydrug.ipynb",
         "plot_polynomial": "simplydrug.ipynb",
         "plot_treatments": "simplydrug.ipynb",
         "plot_curve_raw": "simplydrug.ipynb",
         "plot_curve_mean": "simplydrug.ipynb",
         "pointplot_plate": "simplydrug.ipynb",
         "df_to_table": "simplydrug.ipynb",
         "create_presentation": "simplydrug.ipynb"}

modules = ["core.py"]

doc_url = "https://disc04.github.io/simplydrug/"

git_url = "https://github.com/disc04/simplydrug/tree/master/"

def custom_doc_links(name): return None
